### ISSUE TITLE
01-intro - wording

### ISSUE THREAD

**Issue by ukusormus** [romankuchin/ica0002-2024#1]
[Lab 1 README](https://github.com/romankuchin/ica0002-2024/blob/main/01-intro/README.md) notes on wording / potential confusion:

1. `Once you have completed all the steps above your repository should appear in this list automatically within 2..3 minutes`, but seems like the list updates every 30 min? ([students list](http://193.40.156.67/students.html ) - it first showed 09:00 UTC, then next update was 09:30 UTC) (I updated the page without browser cache)
2. In students list, clicking on my username in the list gave 404 for some time (maybe that could be specified in the README that it's OK, it's still being set up to avoid confusion)?
3. Clicking on my username page, `Complete GitHub repository setup to get your first machine.`, but when in reality, it should be set up correctly already. `Virtual machines are ususally started within 1..2 hours after repository setup is completed` has typo "usu**s**ally" and is hidden behind a dropdown on the username page, could be helpful to specify that information in the README also (step 4 seems to indicate it should be straightforward, and overall README doesn't indicate that you can't do the lab in one go, or maybe could suggest something along the lines of "continue with the next steps before your VM is set up")

Maybe I missed something myself. Cheers

**Comment by ukusormus** [comment]
also, it took some time (~30 min?) after VM was shown on my user's page, but SSH authn did not work (like SSH public key wasn't being added)

unsuccessful
```
debug1: Offering public key: u@github ED25519 SHA256:5nbrEPsWqcPN1AT7UOIZFZqDHaQL0ljdPSrmzuR/ppo agent
debug1: Authentications that can continue: publickey
[...]
debug1: No more authentication methods to try.
ubuntu@193.40.156.67: Permission denied (publickey).
```
successful
```
debug1: Offering public key: u@github ED25519 SHA256:5nbrEPsWqcPN1AT7UOIZFZqDHaQL0ljdPSrmzuR/ppo agent
debug1: Server accepts key: u@github ED25519 SHA256:5nbrEPsWqcPN1AT7UOIZFZqDHaQL0ljdPSrmzuR/ppo agent
Authenticated to 193.40.156.67 ([193.40.156.67]:37022) using "publickey".
```

**Comment by romankuchin** [comment]
1. Fixed
2. 404 shouldn't happen normally, seems something went wrong, but can't reproduce
3. Typo fixed. 
There is already this text: "Note: You don't have to wait until your repository is added to this list, you
can continue with the next task."
