### ISSUE TITLE
01-intro - don't add python venv to path 

### ISSUE THREAD

**Issue by ukusormus** [romankuchin/ica0002-2024#4]
Currently, from 01-intro README:

> Then, add this line to your ~/.profile file (if the file is missing, create it) so you can use 'shorter' commands:
> ```
> PATH="$HOME/ansible-venv/bin:$PATH"
> ```

I don't think it's a good idea, because it will pollute all login shells with `python` and `pip` from the course's virtual environment, not the system-wide Python interpreter and package manager.

Raising the issue out of recent debugging experience while working on an unrelated project, where it took quite some time to understand why I did have access to some system-wide packages, but `pip list` did not show them. (because `pip` was resolved to `/home/u/ansible-venv/bin/pip3.10`)

I'd suggest considering some alternatives, like manually sourcing `ansible-venv/bin/activate` and running `deactivate` when needed, or suggesting some other solution like <https://stackoverflow.com/questions/45216663/how-to-automatically-activate-virtualenvs-when-cding-into-a-directory> (haven't personally tried yet).

It may be too easy to start working on another project days after doing 01-intro in a fresh shell, install packages to the course's virtual env inadvertently (I had actually done that :D), and when deleting the course directory after the course, not understanding where all the packages went. (in a perfect world, all the work would be in separate venvs anyway, but ...)

**Comment by romankuchin** [comment]
We *recommend* to use this way. Feel free to install Ansible whatever way you prefer. We consider this way as the most correct one, if it doesn't work for you then most probably you know what you're doing and you can achieve the desired state using other methods.
