### ISSUE TITLE
LAB 4

### ISSUE THREAD

**Issue by Mabebi29** [romankuchin/ica0002-2024#8]
Hey, I'm having some trouble with Lab 4. It looks like the port forwarding on the host machine isn't set up correctly, both of my ports (39322 and 27822) are forwarding me to the same VM (Mabeib29-2), so I can't access Mabeib29-1 at all. I’ve double-checked my Ansible setup, and everything seems fine on my end. Any chance you could take a look or suggest how I can fix this?

**Comment by romankuchin** [comment]
You're getting to different VMs, try to check with `ip a` for example. VMs just have the same hostname. Set correct hostname with command `hostname` on 1st VM.
