### ISSUE TITLE
04-troubleshooting - GitHub strips HTML tags from README.md Markdown view

### ISSUE THREAD

**Issue by ukusormus** [romankuchin/ica0002-2024#9]
e.g. in plaintext: `Plase use the "<yourname>-2" machine address;`

visually:
![image](https://github.com/user-attachments/assets/71a9786f-f347-4b29-8391-fb7bbd805702)

(search for `<` that is not in code blocks)

**Comment by romankuchin** [comment]
can you create a PR with the fix?
